#spring:
#   #profiles: master
#   application:
#    name: oss-service2
#   #redis:
#    #database: 0
#    #host: localhost
#    #port: 6379
#    #password: 123
#    #timeout: 1000
#    #pool:
#     #max-active: 16
#     #max-wait: 1
#     #max-idle: 8
#     #min-idle: 0
#   datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.26:3306/test?useUnicode=true&characterEncoding=utf-8
#    username: mydb
#    password: mydb123
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 60000
#      auto-commit: true
#      max-lifetime: 180000
#      minimum-idle: 10
#      maximum-pool-size: 20
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#server:
#   port: 9999
#eureka:
#   client:
#     #registerWithEureka: false
#     #fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://192.168.1.182:8888/eureka/,http://192.168.1.182:8889/eureka/
#       #defaultZone: http://master:8888/eureka/